#!/usr/bin/env zsh
vared -p 'enter a address to connect to: ' -c address
vared -p 'amount of pings: ' -c ping
vared -p 'enter a query example(person(id: 1){name}): ' -c query

total=0

for ((i = 0 ; i < $ping; i++)); do
	time=$(curl -w "%{time_total}" -X POST -H "Content-Type: application/json" --data '{ "query": "{$query}" }' -o /dev/null $address)
	echo "request time:  ${time}"
	((total=total+time)) 
done

echo "total time: ${total}"
echo "average roundtrip time: $((total / ping))"
